name: Deploy Fullstack Application

on:
  push:
    branches: [ main ]

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pulumi/actions@v3
      with:
        command: up
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-backend:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy Backend
      run: |
        cd backend
        scp -o StrictHostKeyChecking=no -r * ec2-user@${{ steps.infra.outputs.backend_ip }}:/home/ec2-user/backend
        ssh -o StrictHostKeyChecking=no ec2-user@${{ steps.infra.outputs.backend_ip }} "cd backend && npm install && pm2 start index.js"

  deploy-frontend:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build and Deploy Frontend
      run: |
        cd frontend
        npm install
        npm run build
        aws s3 sync build/ s3://${{ steps.infra.outputs.frontend_bucket }}